const BIO_LENGTH = 500;
const MESSAGE_LENGTH = 500;
const USERNAME_LENGTH = 25;
const CHAT_NAME_LENGTH = 75;
export default {
  BIO_LENGTH,
  MESSAGE_LENGTH,
  CHAT_NAME_LENGTH,
  USERNAME_LENGTH,
};
